[package]
name = "parser"
version = "0.1.0"
authors = ["danielm"]
edition = "2018"
description = "A parser combinator library."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
alloc = []
